# Generated by Django 2.2.6 on 2019-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='temp', max_length=128),
            preserve_default=False,
        ),
    ]
