# Generated by Django 2.2.6 on 2019-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
