# Generated by Django 2.2.6 on 2019-10-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191029_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
